#!/usr/bin/perl
#use strict;
use warnings;
use POSIX;
# Initialize variables

#$lane = $ARGV[0];
#$window = $ARGV[1];
#$window = 100;
#$target_pval = 0.05;
#$bonf_active = 0;
#$target_pval = 0.01;
#$tag_corr = 1;
$cutoff_corr = 1;

#$inputfile = "s_".$lane."_eland_bed";
$inputfile = $ARGV[0];

my $id2tagcount = {};
open(GET_DATA, "< $inputfile") or die "cannot open $inputfile : $!\n";
while(defined($line = <GET_DATA>)) {
	chomp $line;
	@a = split(/\t/, $line);
	$id = $a[3];
	#print @a[2]
	$id2tagcount{$id}++;
	$total_tags++;
}

foreach $id (keys %id2tagcount) {
	$count = $id2tagcount{$id};
	print "$id\t$count\n";
}



exit;


